### ISSUE TITLE
code font weight

### ISSUE THREAD

**Issue by aronatkins** [posit-dev/product-doc-theme#29]
The font / colors used by the theme provide less of a distinction between comments and code. Not sure that we want to make change, but creating this issue to document the change.

With the theme:

<img width="660" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/362187/6c226a79-f64a-4894-8db0-6afc9771b097">

With cosmo:

<img width="663" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/362187/4078ce13-3ae3-47aa-bab8-6fbc6528e9c3">

**Comment by AshleyHenry15** [comment]
I'll look at this one since I'm currently working with the style sheets and messing with the blocks for dark theme

**Comment by AshleyHenry15** [comment]
Connect code color:
`color: #20794D;`

Posit theme ("default") code color
`color: #20794D;`


The comment color is also the same.

The difference may be due to the font styles used - Posit calls for ` $font-family-monospace: "Source Code Pro", monospace;`

The only difference seems to be the font weight/type which is heavier with the theme.

I think that this is going to be a close - don't fix.
